### PR TITLE
Only skip base coverage collection if using same coverage file between branches

### LINKED ISSUE #214: base-coverage-file does not seem to be working
### Describe a bug

Despite providing a file that exists it does not appear to be used.

### Expected behavior

I see a diff with the base report.

### Details

-   Action version: rc-6
-   OS, where your action is running (windows, linux): linux
-   <details><summary>action.yml file</summary>

```yml
on: push
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: ArtiomTr/jest-coverage-report-action@v2.0-rc.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          threshold: 1
          skip-step: all
          annotations: failed-tests
          coverage-file: ./coverage/report.json
          base-coverage-file: ./coverage/base.json
 ```

### Additional context

```
Running using node v14.18.2
Begin initialization stage...
Initialization stage ended
Begin head coverage collection...
Begin installing dependencies...
Installing dependencies skipped
Installing dependencies ended
Begin running tests...
Running tests skipped
Running tests ended
Begin collecting coverage...
Loading code coverage from file: ./coverage/report.json
Collecting coverage ended
Begin parsing coverage...
Parsing coverage ended
Head coverage collection ended
Begin switching to base branch...
Switching to base branch skipped
Switching to base branch ended
Begin base coverage collection...
Base coverage collection skipped
Base coverage collection ended
Begin generating report...
Generating report ended
Begin report publish...
Report publish ended
Begin failed tests' annotations publication...
Failed tests' annotations publication skipped
Failed tests' annotations publication ended
Begin coverage annotations publication...
Coverage annotations publication skipped
Coverage annotations publication ended
```

### PR DESCRIPTION
**Pull request by chrisui**
This PR fixes #214 

The logic behind this change is that if a user has specified separate files for current and base coverage files then they are being explicit in that they don't need to switch between branches to compare the diff of a single file and so we should not need to skip the base coverage collection.

### CODE REVIEW

File: src/run.ts [hunk 1]
```diff
@@ -81,7 +81,7 @@ export const run = async (
         'baseCoverage',
         dataCollector,
         async (skip) => {
-            if (!isSwitched) {
+            if (!isSwitched && options.coverageFile === options.baseCoverageFile) {
```
Comment (ArtiomTr) [inline src/run.ts:84]: I think, that most suitable logic would be:
```ts
if (!isSwitched && options.baseCoverageFile === undefined)
```
Because this logic handles these situations:
* When `baseCoverageFile` is not specified:
   Stage will run depending on result of switching to the base branch, because there is no reason to collect coverage information on the same branch twice.
* When `baseCoverageFiel` is specified:
   Stage will run always.

**Review by ArtiomTr — CHANGES_REQUESTED** [review]
Thank you for the contribution 🚀 
I have a small suggestion for adjusting the implemented logic.

File: src/run.ts (hunk 1 above)
Comment (chrisui) [reply src/run.ts:84]: This logic works for my case. What would happen though if `isSwitched` is true but `baseCoverageFile` is `undefined`, given [L88](https://github.com/ArtiomTr/jest-coverage-report-action/blob/237287b4b4c4a997c912977cfd823514f23abbe6/src/run.ts#L88 uses `baseCoverageFile`?

Perhaps undefined is handled in that func though or this is an impossible state.

Comment (cristian-moreno-ruiz) [reply src/run.ts:84]: If `isSwitched` is true, then the condition that @ArtiomTr is proposing will evaluate to false, no matter what the value of `baseCoverageFile`, so I think it is the proper logic
```suggestion
            if (!isSwitched && options.baseCoverageFile === undefined) {
```

**Review by cristian-moreno-ruiz — COMMENTED** [review]
I am also here waiting for this to be fixed 🙏

**Review by ArtiomTr — APPROVED** [review]
Cool 🚀
